### ISSUE TITLE
Fix component and its routing for 404 Not Found 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#10]
Describe the bug
[App]

The 404 Not Found is not working for any route not found.

To Reproduce

Run the dev server with` npm start` in the root dir. May need to `npm i` or `npm install` the app as I did not include my local node_modules dir. in the upload to GitHub.

Navigate to any route that would not be found.

Expected behavior

Create a 404 Not Found component and routing. 

Desktop (please complete the following information):

Linux, 64bitBrowser [e.g. chrome, safari]
FirefoxVersion [e.g. 22]
107

Additional context

I did add some stub code from an older project but it may not work as it is.

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue.

**Comment by gbowne1** [comment]
Ok @tarunsamanta2k20 I have assigned you to this issue.

**Comment by tarunsamanta2k20** [comment]
@gbowne1 please review my pull request once

**Comment by gbowne1** [comment]
Thia works just fine after checking this out locally.  Merged.
