### ISSUE TITLE
[UPDATE] Fix updates to packages

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#102]
These two packages need updated but may have some breaking changes.  I also was not sure whether to go with @babel or the babel-* packages. See also #68 

> @testing-library/react
> babel-loader 

Noticed as I was installing a package to fix a contribution.

**Comment by mamba-dev-KE** [comment]
Hey, I finally got around to checking out the codebase. I see we have both a webpack config and react scripts (which is currently in use to run the start and build scripts) 

While using React Scripts, all the webpack stuff can be updated by simply installing the latest version of React Scripts. There are multiple solutions to modifying the react scripts (craco and react-app-rewired come to mind)

However, webpack is pretty complex to configure and down the road we could consider maybe migrating to something that's easier to use such as Vite.

**Comment by gbowne1** [comment]
@mamba-dev-KE 

Glad you were able to check out the project.  

All of the packages appear to be up to date.

Webpack can be a pain to configure properly.  I agree.

I want to get a lot of features and a lot of things wired up properly before we make any changes like Vite.

**Comment by mamba-dev-KE** [comment]
Makes sense. I want to take up an issue and help push it all along. Currently looking at the issues.

**Comment by gbowne1** [comment]
We are just getting started and making initial decisions so do not expect much yet.  Theres a number of open issues which have been around a while bordering stale and neec to be re-verified.

I prefer most be made as a group of core contributors come together.

Feel free to submit issues as you see them.

**Comment by Dylan-Clarry** [comment]
Happy to see this issue here, I re-cloned the repo to see the updates people have made and was having problems with packages as well. I agree with @mamba-dev-KE that Vite is a good choice.

I migrated the app to Vite on my local system for fun, zero issues and it's starting up in under 250ms on average.

So yeah, when the time comes my vote is for Vite.

I'll find another issue in the mean time, I got too busy for my issue last week and feel I should make up for it :)

**Comment by Dylan-Clarry** [comment]
Also, [SWC](https://swc.rs/) is a Rust based alternative to babel that's been gaining popularity alongside Vite lately, but we'll burn that bridge when we get to it...

**Comment by gbowne1** [comment]
I feel like it's too soon for Vite and we have so much to get working to even worry about migrating.  

My only worry is performance at this point.  

Current packages need updated whatever the case may be.  I also think Dockerization and/or Kubernetes is a good idea.

**Comment by gbowne1** [comment]
On installing the new login packages.. we still have plenty of package issues.
