### ISSUE TITLE
[BUG] Route '/profile/ directs both to UserProfile.jsx and Profile.jsx component.

### ISSUE THREAD

**Issue by pawel975** [gbowne1/reactsocialnetwork#104]
**Describe the bug**

As issue title says.

**To Reproduce**
1. Clone repo
2. Go to project main directory
3. Write `npm install` in command line to install dependencies
4. Go to http://localhost:3000/profile and see UserProfile component instead Profile

**Expected behavior**

Each component  should render at different route

**Screenshots**

![image](https://user-images.githubusercontent.com/74624831/221537388-30db60be-5f42-40b1-9925-6fee726c49ba.png)

**Comment by shivam1317** [comment]
Hey @pawel975 can i work on this issue?

**Comment by pawel975** [comment]
Sure @shivam1317 I will assign it to you.

**Comment by shivam1317** [comment]
@pawel975 What should be the name of new routes?
or should i do `/userprofile` for `<UserProfile>` component and `/profile` for `<Profile>`

**Comment by pawel975** [comment]
I think it's good idea, but use 'user-profile' instead 'userprofile'
