### ISSUE TITLE
[TODO][FEAT] Add a Notification widget

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#110]
**Is your feature request related to a problem? Please describe.**
No.

Add a notification widget to the Bell notification(s) icon.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by manuel12** [comment]
I can work on this.

**Comment by gbowne1** [comment]
Ok.  The more completed or semi complete stuff we have the better. Thanks!
