### ISSUE TITLE
[TODO] Add better issue and PR labels with a labels.yml 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#112]
**Is your feature request related to a problem? Please describe.**
Yes and no.

Add better issue and PR labeling via labels.yml

**Describe the solution you'd like**
Better labels for Issues and PR's.  While what we have is fine, could triage better with better labels.

**Describe alternatives you've considered**

**Additional context**
Resources:
https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues
https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels
https://docs.github.com/en/github-ae@latest/issues/using-labels-and-milestones-to-track-work/managing-labels
https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28
https://docs.github.com/en/organizations/managing-organization-settings/managing-default-labels-for-repositories-in-your-organization
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/encouraging-helpful-contributions-to-your-project-with-labels

There are also github action(s) in marketplace for this.
https://github.com/marketplace/actions/github-labeler

**Comment by gbowne1** [comment]
This should be done soon

**Comment by Dylan-Clarry** [comment]
Want me to pick this one up since I just updated the templates?

**Comment by gbowne1** [comment]
sure @Dylan-Clarry I think this would greatly enhance the experience with issues, etc.

**Comment by gbowne1** [comment]
More references: 
https://dev.to/envoy_/150-badges-for-github-pnk
https://blog.zenhub.com/best-practices-for-github-issues/
https://blog.adam-marsden.co.uk/better-github-labels-f1360b43e0a
https://handbook.sourcegraph.com/departments/engineering/dev/process/tracking_issues/
https://dev.to/github/programmatically-add-labels-to-your-issues-50dn
https://opensource.guide/best-practices/
https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63
https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues
https://unremarkabletester.com/2021/07/05/small-tips-for-organising-github-labels/

**Comment by Dylan-Clarry** [comment]
Thanks! I'm working on this issue right now

**Comment by gbowne1** [comment]
It's been an issue I have been following for a few years now.  I figured this project would be a great way to learn good methods.

**Comment by gbowne1** [comment]
We should probably work on better milestones as well as we still have plenty, I just did not know what would be best when we started this.

**Comment by gbowne1** [comment]
@Dylan-Clarry it's been a couple weeks. Update?
