### ISSUE TITLE
Fix error: Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>

### ISSUE THREAD

**Issue by manuel12** [gbowne1/reactsocialnetwork#118]
**Describe the bug**
The error appears on the Login component. Is just due to the ```<p>``` elements used on "Register here!"/"Login here!" texts.
The error disappears when we change the ```<p>```  to ```<span>``` elements instead.

**To Reproduce**
1. Go to Login screen.
2. Open console to see the issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/4129325/222556095-1225311a-b973-4920-9d61-5d1332c3facb.png)

**Comment by gbowne1** [comment]
Still has <p> no child errors in my Firefox console even after merge.

**Comment by manuel12** [comment]
Yes, this fix was not included in the last PR. I'm on it now and will create a new PR in a few minutes.

**Comment by gbowne1** [comment]
No worries.  This sort of problem is in https://github.com/gbowne1/SPMS_ERP_MRPUpdatedRepo too.  We never completed the login.  I have hopes and dreams of being able to see the login screen at least. 😂

**Comment by manuel12** [comment]
I think I will check out the other repo when I have time on the weekend, for now I just wanted finish as many issues as I could on this one :)
