### ISSUE TITLE
[TODO] Add a Help feature modal widget

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#124]
**Is your feature request related to a problem? Please describe.**

App is missing a Help center accessible from the user icon menu.

**Describe the solution you'd like**
Routes to /help

**Describe alternatives you've considered**

This could be a whole page, just a widget or a modal, etc. etc.  Facebook's is a whole page

**Additional context**

**Comment by pawel975** [comment]
I will do it, assign myself

**Comment by gbowne1** [comment]
Some inspiration for this:

![Screenshot 2023-03-14 at 14-25-17 Facebook Help Center](https://user-images.githubusercontent.com/47549872/225139922-61b3d045-11ef-4a36-8996-1790ee60592c.png)

**Comment by gbowne1** [comment]
I'm not going to implement Marketplace, Business or Pages.  That could be a whole new app/site.. and I already have so many apps to get done.

**Comment by pawel975** [comment]
Sure, I thought that help center would focus only on mechanisms of updating profile, adding friends etc. I work on creating overall structure and JSON file that is mocked database response of help center categories, subcategories and guides contents.

**Comment by gbowne1** [comment]
Yes, and I already assume some things will need API's built and I am 100% ok with that.

Our help center should be reasonably helpful descriptive and should probably open a help chat to help users with settings, etc.

Since this is a browser app/site..  we need to be sure we are using what the browsers offers us.. keeping in mind security and performance.  So a panel with 4 cards something like the above should be just fine.

**Comment by gbowne1** [comment]
I have more ideas for this but would like to see the first iteration soon.  Ideas? @pawel975 @manuel12

**Comment by pawel975** [comment]
I have done this partially, I plan to finish it within few days
