### ISSUE TITLE
[TODO][Feat] Add Working with images methods

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#127]
**Is your feature request related to a problem? Please describe.**
No.

This feature prerequisites features for adding, uploading,  updating and editing for profile images and avatars.  Including cropping.  

 - Display either an avatar or the users photo in the User Icon / Avatar Icon

**Describe the solution you'd like**
Possibly use Multer or Formik

**Describe alternatives you've considered**

**Additional context**
User Profile `<Profile />` may need to be  completed before this can be done.

**Comment by gbowne1** [comment]
Consider using the https://randomuser.me API or some other picture generator.

**Comment by goutham03062001** [comment]
Hello @gbowne1 . 

I think using cloudinary is very easy and helpful to deal with images instead of multer. I would like to work upon this issue.

And describe me what are all the things you want to achieve?

**Comment by gbowne1** [comment]
I have not used Cloudinary.  I feel like most people working on this would opt for Formik or Multer.  We can always refactor if it ends up not working.  

@pawel975 @manuel12

**Comment by goutham03062001** [comment]
I don't have much experience using Formik & multer. Shall I work with cloudinary?

**Comment by gbowne1** [comment]
This issue needs more scope so closing this as not planned yet.
