### ISSUE TITLE
Fix these minor CSS issues

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#13]
Describe the bug
[App]

Fix these minor CSS issues.

CSS Issue(s):
 - Footer.css: `<Footer class=Footer-body>`
    Error is in browser console. `Error in parsing value for ‘float’.  Declaration dropped.`

 - App.css <.Register-button>
   Error is in browser console. `Error in parsing value for ‘align-items’.  Declaration dropped.`
   This may be moved from App.css to Register.css

 - App.css <.Login-button> 
   Error is in browser console. `Error in parsing value for ‘align-items’.  Declaration dropped.`
   This may be moved from App.css to Login.css

- App.css <.App-header input>
  Error is in browser console `Error in parsing value for ‘padding’.  Declaration dropped.`
  `padding` is currently set to auto.
 
To Reproduce

 May need to `npm i` or `npm install` as I did not include my local node_modules dir in the initial commit & push upload
 run `npm start` in the project root to start the dev server. Browser will open once the dev server is started.

Expected behavior

Working CSS selectors

Desktop (please complete the following information):

    Linux, 64bit
    Firefox
    107

Additional context

**Comment by gbowne1** [comment]
Not sure what to do about the Footer component.  

Most social media sites/apps do not have foooters.

**Comment by MihirRajChowdhury** [comment]
@gbowne1 would it be possible for me to work on this issue

**Comment by gbowne1** [comment]
@MihirRajChowdhury 

   LI'm not too certain what needs fixed but I am assumimg that some of the values like float and align-items could be removed with minimal impact.  I did not try other values to see what may happen.

**Comment by MihirRajChowdhury** [comment]
Thanks for the reply but I wanted to know what type of appearance would you
want it to take.
