### ISSUE TITLE
[TODO] Add panel/UI to create events.

### ISSUE THREAD

**Issue by manuel12** [gbowne1/reactsocialnetwork#133]
**Describe the solution you'd like**
Add a side panel or UI to create personal or group events.

Mockup-wise we can use the current FB UI for inspiration:

![image](https://user-images.githubusercontent.com/4129325/223396359-ad809e11-4449-43d4-9892-f4ae6f6e4fa0.png)

Ours will be a lot less complex at the beginning, but the important thing is to give an UI to create events.

**Comment by gbowne1** [comment]
We also have the two 250px side areas that could be used for event notifications.  This is similar to Facebook and a number of other 3 column social media.  Event creation could be a protected route if the user is a admin, moderator or a owner of a group.

**Comment by gbowne1** [comment]
More inspiration to enhance the Events component experience to include creating events. 

![Uploading Screenshot 2023-03-14 at 12-40-02 Events Near Me Facebook.png…]()

**Comment by gbowne1** [comment]
Events also need to be shareable with a share icon.

![Screenshot 2023-03-14 at 14-08-27 Events Near Me Facebook](https://user-images.githubusercontent.com/47549872/225136739-15cdb4db-e637-4239-aaef-10a7f33a6599.png)

**Comment by gbowne1** [comment]
@pawel975 can you please review the PR?

**Comment by pawel975** [comment]
> @pawel975 can you please review the PR?

Sure, I can do it tomorrow

**Comment by gbowne1** [comment]
Ok great. Thanks. Just checking in.  I want to get a bunch of stuff done this week.

**Comment by pawel975** [comment]
> Ok great. Thanks. Just checking in.  I want to get a bunch of stuff done this week.  

I get it, last weeks I'm busy but I want to come back to contributing more regularly soon 😀
