### ISSUE TITLE
[TODO] Add Snackbar Toast feature

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#135]
**Is your feature request related to a problem? Please describe.**
No, just a UI/UX solution.

Add a MaterialUI <Snackbar /> component to provide Toast style popper notificatons where it is meaningful, like Login Success, etc.

https://mui.com/material-ui/react-snackbar/
https://mui.com/material-ui/api/snackbar/

**Describe the solution you'd like**
There may be some useful cases like on Mobile where a Toast notification via MUI Snackbar would be useful.  This would be a great implementation to work on.

**Describe alternatives you've considered**

**Additional context**

**Comment by manuel12** [comment]
We can definitely create a component specific to this. I added a CustomAlert component that is being used in Login page now. 
I can add a custom snackbar that can be used as notification.

**Comment by gbowne1** [comment]
Yeah, I can see MUI Snackbars being useful in many places.

**Comment by manuel12** [comment]
I will try creating this feature and applying to event creation success and event delete success.

**Comment by gbowne1** [comment]
Alright :) sounds good to me.  I reviewed your PR.  Looks great! :smile: 

I do think there's plenty of opportunity to use Snackbars.  I looked at react-toast things and they did not seem to really fit our needs without implementing a lot of special things when MUI carries Snackbars

**Comment by gbowne1** [comment]
@manuel12 It's been a week for this, what are your ideas?

**Comment by manuel12** [comment]
> @manuel12 It's been a week for this, what are your ideas?

I'm creating a Custom component that is customizable and apply it on Login and Event creation. I hope I can have it ready on the first half of this week.

**Comment by gbowne1** [comment]
Ok thats great! Can't wait to see what you have. @manuel12

**Comment by manuel12** [comment]
Created PR https://github.com/gbowne1/reactsocialnetwork/pull/150 @gbowne1 @pawel975

**Comment by manuel12** [comment]
Fixed by https://github.com/gbowne1/reactsocialnetwork/pull/150
