### ISSUE TITLE
[BUG] Theme mode resets on reloads

### ISSUE THREAD

**Issue by pawel975** [gbowne1/reactsocialnetwork#138]
**Describe the bug**

As title says.

**To Reproduce**
1. Go to '/'
2. Click on theme switch to switch to dark mode
3. Go to "Events"
4. See that theme resets to light mode.

**Expected behavior**

App state should remember theme mode on reloads, possibly we can save it in local storage.

**Comment by pawel975** [comment]
I will handle it on days.

**Comment by gbowne1** [comment]
Yeah I noticed this too.  There's some FOUC too when the drawer opens.

**Comment by gbowne1** [comment]
Good idea to put this in local storage.  I like that idea.

**Comment by manuel12** [comment]
Also agree on using localStorage.
