### ISSUE TITLE
Fix routing.

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#14]
Describe the bug
[App]

Fix the routing.  Installed are:
  react-dom
  react-router-dom
  react-router

There is also an error message in the browser console. 
`No routes matched location "/" `

To Reproduce:

May need to npm i or npm install as I did not include my local node_modules dir in the initial commit & push upload
run npm start in the project root to start the dev server. Browser will open once the dev server is started.

Expected behavior

Desktop (please complete the following information):

Linux, 64bit
Firefox
107

Additional context:
Not sure how much routing can be done without too much work completed already because not many components have been done so far.  But as below, see https://github.com/gbowne1/reactsocialnetwork/discussions/15 for routing.

**Comment by maddy020** [comment]
Hey @gbowne1 
I would like to contribute to this issue 
Please elaborate which file need this fixing

**Comment by gbowne1** [comment]
@maddy020 

I don't know how familiar you are with React 17 && 18.  

There are some hints to what I believe is needed in the discussions tab, here. 
https://github.com/gbowne1/reactsocialnetwork/discussions/15

**Comment by gbowne1** [comment]
Still needs a lof of routes fixed and added but the main issue here was fixed.
