### ISSUE TITLE
Login page input labels missing proper contrast on dark mode.

### ISSUE THREAD

**Issue by pawel975** [gbowne1/reactsocialnetwork#140]
**Expected behavior**

Text should be more visible especially that app is directed do older people.

**Screenshots**

![image](https://user-images.githubusercontent.com/74624831/224412272-11b68774-0851-432f-b1f1-66e3498d0d85.png)

**Comment by gbowne1** [comment]
It's actually not bad as far as colors go.  But, yes even if you set aside the use case(s) it could be even better

**Comment by manuel12** [comment]
I'll look into this.

**Comment by gbowne1** [comment]
As I said before its great.  I showed screenshots it to a few people and they loved it.
