### ISSUE TITLE
[Bug]: Create a new Event bug

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#149]
### Describe the Bug

While creating a new event, the event created fine, but the data/text at the right of the pic of the event do not end up being/looking exactly like the current examples.  See the screenshot.  

### Steps to Reproduce

Start the Create-React-App development server with `npm start` after installing with `npm i` or `npm install`.

Navigate to /events or click on the Events in the left nav drawer after opening it with the hamburger menu.

Click on Create Event..

Fill out the event data.. 

### Screenshots

![Screenshot 2023-03-27 at 17-12-42 React Social Media App](https://user-images.githubusercontent.com/47549872/228095226-a4b43139-af16-4929-980c-c674a27919cd.png)

### Which device are you using?

Desktop

### Which operating system are you using?

Linux

### Which browser are you using?

Firefox 111

### Additional Context

I didn't look at the console too see if anything actually completed.  This might just be a CSS issue.

### Contribute

- [ ] I am willing to contribute and submit a pull request

**Comment by manuel12** [comment]
@gbowne1  What data was used to create the event?

**Comment by gbowne1** [comment]
I just used random data in the fields of the form.  No matter what I tried made the text appear in a vertical column like that.  I tried 3 times be to be sure it wasnt just a random bug.

I used Mountain Mauling for the event title and Top of the mountain for location and a random date.

**Comment by manuel12** [comment]
Ok I can make the text take a more wide space.

**Comment by gbowne1** [comment]
I wasnt sure if you meant it to be like that but yeah I only noticed that the created event did not end up looking like the 3 example events.
