### ISSUE TITLE
[Bug]: "X" close icon in dark mode is hard to see

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#152]
### Describe the Bug

In all of  the components panels, the "X" close icon in dark mode is hard to see in dark mode only.

### Steps to Reproduce

Start the development server with `npm start` after installing with npm i or npm install, if it is not already installed.

### Screenshots

Edit: this is the screenshot 
![Screenshot 2023-04-02 at 16-02-06 React Social Media App](https://user-images.githubusercontent.com/47549872/229383758-9f6a347c-0130-41c5-aeea-1dd3e0c3b382.png)

### Which device are you using?

PC, 32gb RAM, intel Core  i7 3rd Gen.

### Which operating system are you using?

Linux, Debian Base, x64

### Which browser are you using?

Firefox 111

### Additional Context

Problem exists in all panel components only in dark mode.  The SideNav X is fine and visible in dark and light.

### Contribute

- [ ] I am willing to contribute and submit a pull request

**Comment by munnokd** [comment]
Please assign this issue to me. So I will fix this issue.

**Comment by gbowne1** [comment]
ok @munnokd 

Make sure to screenshot the change.  Thank you.

**Comment by munnokd** [comment]
Thank you for assigning this issue to me I will fix this issue.

**Comment by gbowne1** [comment]
To be done later on.   This is a minor Issue.  Closing this as not planned and resolved.
