### ISSUE TITLE
[Bug]: Bugs in Events.jsx and SingleEvent.jsx

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#153]
### Describe the Bug

After merging the latest PR we get these errors from ESLint from Events.jsx and SingleEvent.jsx

[eslint] 
src/components/Events.jsx
  Line 68:6:  React Hook useEffect has a missing dependency: 'eventsFilterValue'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

src/components/SingleEvent.jsx
  Line 74:30:  The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/HEAD/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in [eslint] 
src/components/Events.jsx
  Line 68:6:  React Hook useEffect has a missing dependency: 'eventsFilterValue'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

src/components/SingleEvent.jsx
  Line 74:30:  The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/HEAD/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid

webpack compiled with 1 warning

### Steps to Reproduce

Start the react development server with npm start after installing with npm install

### Which device are you using?

PC Desktop, x64 Core i7 3rd Gen

### Which operating system are you using?

Linux

### Which browser are you using?

Firefox 111

### Contribute

- [ ] I am willing to contribute and submit a pull request

**Comment by martinyis** [comment]
Hey @gbowne1, I would like to work on this issue.

**Comment by gbowne1** [comment]
Ok @martinyis.  I will assign you to this issue.

**Comment by gbowne1** [comment]
Closed with recent merge #155
