### ISSUE TITLE
[feature]: Add an AdminDashboard component

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#170]
### Is your feature request related to a problem? Please describe.

There needs to be a Admin dashboard:

Here is my proposed code including CSS for this component.

```jsx
import React, { useState, useEffect, useLayoutEffect, useMemo, useCallback } from 'react';
import PropTypes from 'prop-types';
import { useHistory, useLocation, useNavigate, useParams, Navigate, Outlet, Link, Breadcrumbs } from 'react-router-dom';
import { Box, Button, IconButton, Pagination, Typography, TextField } from '@mui/material';
import CloseIcon from '@mui/icons-material/Close';
import HeartIcon from '@mui/icons-material/Favorite';
import ThumbUpIcon from '@mui/icons-material/ThumbUp';
import ThumbDownIcon from '@mui/icons-material/ThumbDown';
import TagIcon from '@mui/icons-material/LocalOffer';
import { isAuthenticated } from '../helper/auth';

import './AdminDashboard.css';

const AdminDashboard = ({ }) => {
  const history = useHistory();
  const location = useLocation();
  const navigate = useNavigate();
  const params = useParams();

  // Your useState, useEffect, and other hooks here

  return (
    <Box className="AdminDashboard" sx={{ minWidth: '1318.8px', minHeight: '700px' }}>
      <Box className="AdminDashboard-header" sx={{ minHeight: '60px' }}>
        <IconButton>
          <CloseIcon />
        </IconButton>
        {/* Add other header elements here */}
      </Box>
      <Box className="AdminDashboard-content">
        {/* Buttons */}
        <IconButton>
          <HeartIcon />
        </IconButton>
        <IconButton>
          <ThumbUpIcon />
        </IconButton>
        <IconButton>
          <ThumbDownIcon />
        </IconButton>
        <IconButton>
          <TagIcon />
        </IconButton>
        <Button variant="contained" color="primary" onClick={onBanUser}>
          Ban User
        </Button>
        <Button variant="contained" color="primary" onClick={onAddUser}>
          Add User
        </Button>
        <Button variant="contained" color="primary" onClick={onEditUser}>
          Edit User
        </Button>
        <Button variant="contained" color="primary" onClick={onAuthorizeUser}>
          Authorize User
        </Button>
        <Button variant="contained" color="primary" onClick={onEditComment}>
          Edit Comment
        </Button>

        {/* Text area */}
        <Box sx={{ display: 'flex', flexDirection: 'column', mt: 2 }}>
          <Typography variant="h6">Write a post:</Typography>
          <TextField
            multiline
            rows={4}
            variant="outlined"
            placeholder="Write your post here..."
          />
          <Box sx={{ display: 'flex', justifyContent: 'flex-end', mt: 1 }}>
            <Button variant="contained" color="primary">
              Post
            </Button>
          </Box>
        </Box>

        {/* Pagination and breadcrumb */}
        <Box sx={{ display: 'flex', justifyContent: 'space-between', mt: 3 }}>
          <Breadcrumbs>
            <Link color="inherit" href="/">
              Home
            </Link>
            <Link color="inherit" href="/admin">
              Admin
            </Link>
          </Breadcrumbs>
          <Pagination count={10} />
        </Box>
      </Box>
    </Box>
  );
};

AdminDashboard.propTypes = {
  onBanUser: PropTypes.func,
  onAddUser: PropTypes.func,
  onEditUser: PropTypes.func,
  onAuthorizeUser: PropTypes.func,
  onEditComment: PropTypes.func,
};

export default AdminDashboard;
```

Your thoughts @manuel12 @Dylan-Clarry @pawel975 ?

### Describe the solution you would like

We  can then talk about what we need for admin.

### Describe the alternatives you have tried

I looked at other apps for some thoughts.

**Comment by goutham03062001** [comment]
Hello is this issue still open?

I would like to work upon this issue.

Let me know what exactly you are planning to put on admin Dashboard. Please describe it clearly. So that i can get to know what you are trying to achieve. If anything need to address I'll let you inform that.

Please respond asap.

**Comment by gbowne1** [comment]
Yes this is still open. This is a pretty complex issue. 

Have you started the app yet?

I would like anyone working with the admin dashboard to start with code I proposed above.

We can iterate through the design of the UI or the component. 

 It will look and be styled like the dashoard component that renders when you first start the app as it is currently

The components are all in /pages/ so you would add a /AdminDashboard folder to /pages and inside there add a AdminDashboard.jsx and copy the above code to that file and put the .css file in with the other .css files for the components.  (Note will edìt with the actual css file location when able to tomorrow.)

The component is very complex.  It will be paginated within the components panel.  It will need some pagination and breadcrumbs or tabs in the section under the component header.

It needs a page or a separate part of this to do user CRUD as well as buttons for to add, edit moderate and ban users.

It needs a page to create posts, with common editor controls and a text area with a heart, thumbs up/thumbs up, ability to add tags with a button.   And a  selection for creating posts in the feed or in the users main blog post

We can iterate through this design if its too comolex.

There will be a separate dashboard the users who are not moderators or admins especially of the Groups pages. This is what already renders when you start the app or go to /dashboard.

Let us know. Thanks.

@pawel975 @manuel12

**Comment by gbowne1** [comment]
@goutham03062001 I have a Slack channel for this, go click on the Issues Tab and click on the green New Issue button, the Slack link is at the bottom of the panel.

**Comment by gbowne1** [comment]
As for admin features, I would like:

* Admin & Moderation tools
  - CRUD for users (Creating, Editing/Updating, Deleting or Banning/UnBanningusers)
* Blog and post (Feed) tools 
  - CRUD for posts and blogs.
* Editor panel (considered using Lexical or Slate)
* Events
* Groups
  - Mainly CRUD type stuff. 
  - Used on the public side for group admins, mods, owners, maintainers to do CRUD work on the group.
  - An abstraction is that say the group is for Age 18-49.  It should not let anyone join the group that is outside that age 
    range, and maybe it should suggest groups that are in their age range

**Comment by gbowne1** [comment]
Assigning myself to this issue. Am working on getting this to work.  Already have the code we have visible on my local.  Having some problems with placement.  Everything is ending up centered in the view. It won't align or justify left.

Am considering using the whole view for this feature instead of panel because of the amount of features this will have, at least so we can iterate through design.

**Comment by gbowne1** [comment]
@manuel12 Do you think we could do 3 different size panels? The one we have now would be medium, the other being small and a full width panel being large.

**Comment by gbowne1** [comment]
Going to have to figure out how to get the admin panel to be a protected route.  It shouldnt be displayed unless the user is a admin or moderator.

We will need logins for both admin and mod.

**Comment by gbowne1** [comment]
Closing this AdminDashboard panel component as added
