### ISSUE TITLE
[Bug]: This project needs a ESLint and Prettier configuration 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#172]
### Describe the Bug

We have a small problem with various usage of double and single quotes, indentation, tabs and spaces, etc. across the entire project.  

We need to decide on what to use epecially for JSX but I prefer using the rules in the standard, unless there is a specific reason we need to diverge from the standard for JSX.

I use Prettier and ESlint to lint and prettify the files.

This will keep people from making the minor changes in a PR to the quoting and indentation, etc.

### Steps to Reproduce

Too many issues with this in various files to mention all of them. We will need to go through and re-Prettify and Re-Lint all of the files in the project.

I proposed some code in the section Additional Context below.  It will need to be tested.  We might need to install some of the plugins as well as I think devDependencies?

### Which device are you using?

PC Desktop, x64 Core i7 3rd Gen

### Which operating system are you using?

Linux x64, Debian Base

### Which browser are you using?

Firefox 111

### Additional Context

Here are my proposed files:

.eslintrc

```
{
  "parser": "babel-eslint",
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:prettier/recommended",
    "prettier/react"
  ],
  "plugins": ["react", "prettier"],
  "rules": {
    "prettier/prettier": "error",
    "react/jsx-uses-react": "off",
    "react/react-in-jsx-scope": "off",
    "semi": ["error", "always"],
    "quotes": ["error", "double"]
  },
  "settings": {
    "react": {
      "version": "detect"
    }
  },
  "env": {
    "browser": true,
    "node": true,
    "es6": true
  }
}
```

.prettierrc
```
{
  "semi": true,
  "singleQuote": false
}
```

### Contribute

- [X] I am willing to contribute and submit a pull request

**Comment by gbowne1** [comment]
@pawel975 @manuel12

**Comment by gbowne1** [comment]
I tested my proposed code today during lunch. Seems to work fine. I can make a PR. We can always modifty it so that it does work.

**Comment by pawel975** [comment]
Looks good to me!

**Comment by gbowne1** [comment]
Ok @pawel975  I will do a PR as soon as we clear up the other PRs.  will wait for Manuel

**Comment by manuel12** [comment]
Looks good to me too!
