### ISSUE TITLE
[Bug]: Needs a code cleanup

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#183]
### Describe the Bug

Now that we have a ESLint and Prettier config.  The code needs to be re linted and prettified with Prettier and ESLint

### Steps to Reproduce

N/A.

This is a code style issue.

### Which device are you using?

PC

### Which operating system are you using?

Linux

### Which browser are you using?

Firefox 111

### Contribute

- [ ] I am willing to contribute and submit a pull request

**Comment by promise-dash** [comment]
Hey, I would like to resolve this. Could you please assign this issue to me?

**Comment by gbowne1** [comment]
This will need the ESLint and Prettier configuration fixed. You are welcome to work on it.  Iadded at least one issue about this particular issue/bug.  They are all similar issues.

  See if you can get it to lint and prettify the code properly especially for JSX which we use for components.

I will assign you 

Thanks @promise-dash
