### ISSUE TITLE
[Bug]: Needs updated packages 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#185]
### Describe the Bug

We do have a few packages we need to have uodated and a few we are not using.

Update the packages and remove the ones we are not using.

### Steps to Reproduce

This is a package update issue.

### Screenshots

Run npm outdated to see a table outdated in your console or terminal then run npm update.  

### Which device are you using?

PC

### Which operating system are you using?

Linux

### Which browser are you using?

Firefox 111

### Additional Context

This is a side issue related to an earlier one related to packages.

### Contribute

- [ ] I am willing to contribute and submit a pull request

**Comment by promise-dash** [comment]
Hey, I would like to resolve this issue. Could you please assign this issue to me?

**Comment by gbowne1** [comment]
Ok, @promise-dash you can work on this.  Thanks.
