### ISSUE TITLE
[feature]: Create express backend

### ISSUE THREAD

**Issue by manuel12** [gbowne1/reactsocialnetwork#212]
### Is your feature request related to a problem? Please describe.

We need a backend, this will be the initial implementation. It will be located in a folder called /backend.

### Describe the solution you would like

  I will use an express backend and a Sqlite3 db. This way we will be able to store users and events.

### Describe the alternatives you have tried

N/A

**Comment by gbowne1** [comment]
I would probably use /server and /db or /data 

/src/client and /src/server is standard in full stack projects.

It will be nice to have a backend

**Comment by manuel12** [comment]
> I would probably use /server and /db or /data
> 
> /src/client and /src/server is standard in full stack projects.
> 
> It will be nice to have a backend

Definitely, I will name them that way then.
