### ISSUE TITLE
[Bug]: Babel issue with new client

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#218]
### Describe the Bug

With the new client & server structure we have /client and /server.

I get a bunch (about a dozen) of this error from ESLint.

```shell
[eslint] 
src/App.js
  Line 0:  Parsing error: No Babel config file detected for /media/gbowne1/18656299-5992-400a-a7a4-b6ffc4b0612f/Documents/reactsocialnetwork/client/src/App.js. Either disable config file checking with requireConfigFile: false, or configure Babel so that it can find the config files
``` 

### Steps to Reproduce

cd to client
run npm start
in another terminal/console 
cd to server
run npm start

wait till the server runs the app.

### Screenshots

![Screenshot 2023-05-23 at 13-03-44 React Social Media App](https://github.com/gbowne1/reactsocialnetwork/assets/47549872/6a69b24b-cd5d-493a-8296-6003f313fcae)

### Which device are you using?

PC Desktop, x64 Core i7 3rd Gen

### Which operating system are you using?

Linux x64, Debian Base

### Which browser are you using?

Firefox 112

### Contribute

- [ ] I am willing to contribute and submit a pull request

**Comment by manuel12** [comment]
In the push I did fixing https://github.com/gbowne1/reactsocialnetwork/issues/223 I also moved the .babel config file from root folder to client folder, should be fixed now.

**Comment by gbowne1** [comment]
Ok great. :-)
