### ISSUE TITLE
[Bug]: The Login panel has a CSS issue

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#221]
### Describe the Bug

The Login modal/component/panel has an issue with the CSS of the labels for the fields while the user is in dark mode.  The label extends beyond the light background of the field(s) into the dark background above the field.  Consider changing the field background.

See the screenshot

### Steps to Reproduce

Start the development server.

### Screenshots

![Screenshot 2023-05-23 at 13-49-51 React Social Media App](https://github.com/gbowne1/reactsocialnetwork/assets/47549872/2b3b906f-e91f-44e9-a166-b3e746361606)

### Which device are you using?

PC Desktop, x64 Core i7 3rd Gen

### Which operating system are you using?

Linux x64, Debian Base

### Which browser are you using?

Firefox 112

### Contribute

- [ ] I am willing to contribute and submit a pull request

**Comment by manuel12** [comment]
I'll take care of this.
