### ISSUE TITLE
[Bug]: No route or method to get to /profile

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#222]
### Describe the Bug

We are currently working on the user's profile display page as well as the page that allows the user to create a profile.

However, the /profile route 404's.  

I think there was once a /user-profile route this will be confusing if it still exists.

We will also need a /profile/create route which I think would be better that would be currently at http://localhost:3000/profile/create.

Although a stub of this issue exists, this is the issue for the actual route not working.

There is another separate issue to put access to the user's profile in the UI.  
Where should the user access their profile from? My thought was from the user icon

### Steps to Reproduce

cd to /server
run npm start

in another terminal 
cd to /client
run npm start

### Which device are you using?

PC Desktop, x64 Core i7 3rd Gen

### Which operating system are you using?

Linux x64, Debian 11 Base

### Which browser are you using?

Firefox 112

### Contribute

- [ ] I am willing to contribute and submit a pull request

**Comment by swarajsahil** [comment]
Assign it to me i will try to fix it

**Comment by gbowne1** [comment]
@swarajsahil are you still working on this?

**Comment by gbowne1** [comment]
Ok, should I reassign this?

**Comment by swarajsahil** [comment]
Okay

**Comment by gbowne1** [comment]
There is a route for /profile.  closing this issue with a recent merge that added a Create User Profile page on this route.
