### ISSUE TITLE
[Bug]: Login route persists after user is logged in and or registered

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#223]
### Describe the Bug

Login route persists after user is logged in and or registered.  It still is /login and the page that is displayed shows 404 Not Found.

The new forwarded or redirected route should be the root route with or without the /

Side note here, /register does correctly shows the register section of the login/register component.

When logged in, the root route shows the login component.  The root route should show the main feed, including other users' posts, microblogs, activities, etc, etc. etc.

### Steps to Reproduce

Start the development server by

cd to /server
run npm start

then in another terminal/console
cd to /client
run npm start

### Which device are you using?

Linux VM Server

### Which operating system are you using?

Linux x64, Debian Base

### Which browser are you using?

Firefox 112

### Contribute

- [ ] I am willing to contribute and submit a pull request

**Comment by manuel12** [comment]
@gbowne1  I pushed a hotfix to main solving this issue and added e2e tests to check this. Should be ok now.

**Comment by gbowne1** [comment]
Ok great. :-)
