### ISSUE TITLE
[feature]: create a reuseable Modal component

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#226]
### Is your feature request related to a problem? Please describe.

We may need a few modals in the future, so make things easier for anyone wanting to add a new modal to their feature especially anyone new to the project.

This custom, reusable component could be resizeable in some fashion through CSS

### Describe the solution you would like

Create a fully customizeable, reuseable modal componend called <Modal /> that couod be boilerplated for reuse.

### Describe the alternatives you have tried

N/A

**Comment by manuel12** [comment]
I can take this.
