### ISSUE TITLE
Add 404 / NotFound component

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#23]
**Describe the bug**

I had to change the background color to black to see this, but the 404/NotFound component is rendering to the view.. (see the Screenshot below) and when you navigate to a route (picked a random one).. doesn't actually display.. the 404/NotFound route should be <url>/404 or something similiar.

**To Reproduce**

Run the dev server with npm start in the root dir. May need to npm i or npm install the app as I did not include my local node_modules dir. in the upload.

**Expected behavior**

Working 404 / Not Found page.

**Screenshots**

![Screenshot 2023-01-29 at 16-55-23 React Social Media App](https://user-images.githubusercontent.com/47549872/215368635-8a819543-86c5-4ee6-81d4-cfcf28db99e1.png)

**Desktop (please complete the following information):**
   Linux, x64
   Firefox
   107

**Additional context**

**Comment by MihirRajChowdhury** [comment]
do I need to only let it display this "Working 404 / Not Found page." in the 404 not found file

**Comment by gbowne1** [comment]
A working version of this would not only 404 in the browser console, but actually display something like:

Oops, Sorry we were unable to find your page!

404 Not Found

in the redirected view...

**Comment by gbowne1** [comment]
Changed this  temporarily to show the sidebar.

**Comment by gbowne1** [comment]
This is temporarily fixed.  Needs a little more work with routing though
