### ISSUE TITLE
[Bug]: Fix the Help component's CSS

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#230]
### Describe the Bug

The Help panel accessible at /help or through the user icon needs some CSS work.

There is no alignment to the right side of the panel, so it extends beyond the rightwhat normally would be the panel.

I screenshotted the right side to show this area.

The entire panel with the panel header should be roughly 1300px x 700px and have some side margin to both left and right side.

### Steps to Reproduce

Start the development server 

cd to /server
run npm start

in another terminal 
cd to /client
run npm start

wait for the app to start in your browser.

go to the user icon and select Help or manually go to /help route.

### Screenshots

![Screenshot 2023-05-25 at 22-46-51 React Social Media App](https://github.com/gbowne1/reactsocialnetwork/assets/47549872/f1573df8-80f8-4750-bd63-db21327bba38)

### Which device are you using?

PC, Desktop, Intel Core i7-3770k

### Which operating system are you using?

Linux x64, Debian 11 Base

### Which browser are you using?

Firefox 112

### Contribute

- [ ] I am willing to contribute and submit a pull request

**Comment by NigamDevansh** [comment]
may I work on this issue if its not assigned.
@gbowne1

**Comment by gbowne1** [comment]
yes you can @NigamDevansh

**Comment by NigamDevansh** [comment]
Below are the screen shots attached.
Is this correct ? please let me know @gbowne1 
![Screenshot 2023-06-01 175644](https://github.com/gbowne1/reactsocialnetwork/assets/88497388/94c8d000-34d9-43d8-9e98-b7ff721fe740)
![Screenshot 2023-06-01 175716](https://github.com/gbowne1/reactsocialnetwork/assets/88497388/2913db39-fc15-4a5a-9ca9-2d6bcf79cdfd)

**Comment by gbowne1** [comment]
@NigamDevansh yes that is correct.

**Comment by gbowne1** [comment]
I looked at your PR. It is huge.  It included all the other previous commits by other developers.

Somehow your PR included more than just your commit which took me a while to find.

I would suggest you redo it so that it only will have your commit.

Please also include a screenshot of your working change in your PR.

We have a document describing how to contribute in /docs folder/directory. Please let us know how we could make that better.

**Comment by NigamDevansh** [comment]
So sorry will fix it now and redo the PR

**Comment by NigamDevansh** [comment]
Please check now. @gbowne1 
I have added the screenshots too.

**Comment by NigamDevansh** [comment]
I read that actually and thought i have to push it to test branch.

**Comment by gbowne1** [comment]
No, it does not need to go to a test branch.  Test branch is for small untested features or code not ready for production or things we are testing.  Perhaps that was not clear.  if it was not clear I can flag that for review.

**Comment by NigamDevansh** [comment]
oh got it. I don't think so it need to be flagged, I just misunderstood.

**Comment by gbowne1** [comment]
I just added an issue for this.  We are still doing our documentation, so it might still be a bit ambiguous or not very clear.

I am considering adding documentation in other languages.

**Comment by NigamDevansh** [comment]
documentation in other languages, that sounds great.

**Comment by gbowne1** [comment]
yeah.  I added an issue for that.  @NigamDevansh 

Feel free to contribute.
