### ISSUE TITLE
App still loads index.css

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#24]
**Describe the bug**
[App][CSS Styling] 

 This app is loading the index.css in the browser.

The browser console logs an error as:
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped.

**To Reproduce**
May need to `npm i` or `npm install` as I did not include my local node_modules dir in the initial commit & push upload
run `npm start` in the project root to start the dev server. Browser will open once the dev server is started.

**Expected behavior**

App should use only App.css and CSS framework dependent CSS files.

**Desktop (please complete the following information):**
   Linux, x64 
   Firefox
   107 

**Additional context**

**Comment by MihirRajChowdhury** [comment]
[gbowne1] would it be okay if I remove index.css from the index.js file so that it will not import it and only import App.css

**Comment by gbowne1** [comment]
@MihirRajChowdhury 

Sure, I think that should fix it.

I only noticed it because it was trying to do the moz webkit stuff for font smoothing on the body node.
