### ISSUE TITLE
[feature]: Internal & External APIs

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#251]
### Is your feature request related to a problem? Please describe.

We do not have any REST APi's. Create some internal and/or external APIs for:

- Users
- Events
- Groups
- Posts

Not sure yet what else we will need as far as APIs.

The backend should have some consumeables we can use.

### Describe the solution you would like

People may want to schedule posts, check anyltics, etc. among other things using other apps or sites.

We should provide both internal and external APIs 

The internal API would be used for components, user data, posts and external API would be used/consumed outside of the app by other services, apps or sites.

### Describe the alternatives you have tried

Some social media apps like Facebook, Instagram, LinkedIn, Reddit, etc are providing extermal APIs, and may have plenty of internal APIs.

**Comment by manuel12** [comment]
@gbowne1 I can document the APIs we currently have on the wiki pages.

**Comment by gbowne1** [comment]
that will be great! Thanks @manuel12 :smile:  :+1:

**Comment by manuel12** [comment]
@gbowne1 Here are the current back-end APIs documented: https://github.com/gbowne1/reactsocialnetwork/wiki/Routes-&-Endpoints#back-end-routes

**Comment by gbowne1** [comment]
Great job on those @manuel12 Thank you!
