### ISSUE TITLE
[TODO] Add close "X" icon to close panels/components

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#26]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Close "X" button on all panels, i.e. Dashboard, User Profile, etc. so that the user can close them.

**Describe alternatives you've considered**

- Closing the panels by clicking on the menu choice again.
- Tabbed panels

**Additional context**

**Comment by KaptainCS3** [comment]
!assign

**Comment by gbowne1** [comment]
@KaptainCS3 are you wishing to get assigned to this task?

**Comment by KaptainCS3** [comment]
yes

**Comment by gbowne1** [comment]
Ok.

**Comment by newdydx** [comment]
@gbowne1 can I be assigned to work on this??

**Comment by gbowne1** [comment]
Ok. @newdydx

**Comment by newdydx** [comment]
@gbowne1 please if there is any issue you can always inform me so i will work on it. Thanks

**Comment by gbowne1** [comment]
Ok @newdydx 

I will review your PR. 

Thanks.

**Comment by newdydx** [comment]
@gbowne1 I will be expecting...thanks

**Comment by gbowne1** [comment]
I really need to update the PR and contributing guidelines on branches. 

We use a hybrid of Git flow and Github flow.  Read this: 
https://www.alexhyett.com/git-flow-github-flow/

**Comment by gbowne1** [comment]
Alright.. merged. Forgot to reopen too.  Thanks for the PR @newdydx 😀

**Comment by newdydx** [comment]
@gbowne1 Thanks a lot for this... and I am a junior frontend developer looking for an internship role to gain more experience so if by any chance you have the privilege please I am open for the role.

**Comment by gbowne1** [comment]
No worries @newdydx  I expect this project to get decent following. Make sure to star and watch it on GitHub.

I am looking for people to:

- work on bugs
- work on adding features
- QA/QC (so review PRs, etc
- work on CSS
- work on accessibility
- backend work
- making the marketing page
- work on releases
- work on TODOs (theres 30 of them at least

Please review the contributing.md document
