### ISSUE TITLE
[Bug]: CreateEventModal has CSS imported on wrong line

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#260]
### Describe the Bug

ESLint says "Import in body of module; reorder to top." :

 import "./CreateEventModal.css";

 is on line #20

```shell
[eslint] 
src/pages/Events/CreateEventModal/CreateEventModal.jsx
  Line 20:1:  Import in body of module; reorder to top  import/first
```

### Steps to Reproduce

Run lint on the currently existing code

### Which device are you using?

PC, Desktop, Intel Core i7-3770k

### Which operating system are you using?

Linux x64, Debian 11 Base

### Which browser are you using?

Firefox 112

### Contribute

- [ ] I am willing to contribute and submit a pull request

**Comment by manuel12** [comment]
I'm making a fix for the e2e tests that will also include this fix, so I can take this.

**Comment by gbowne1** [comment]
Ok @manuel12 I have no idea where or at which point this error crept in at.

I only noticed when I went to go lint the project
