### ISSUE TITLE
[CSS] Fix right side of components

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#28]
**Describe the bug**
The right side of the component panels are white.making them look a bit odd in the view

**To Reproduce**
May have to `npm i` or `npm install` as I did not include my local node_modules.  Then run the dev server by using `npm start`. The browser will start and render the view to localhost:3000

**Expected behavior**

**Screenshots**
![Screenshot 2023-02-15 at 22-48-56 React Social Media App](https://user-images.githubusercontent.com/47549872/219289565-b4490f6f-6fbf-4592-bbd9-17bf9ef24210.png)

**Desktop (please complete the following information):**
    Linux, x64
   Firefox
   107

**Additional context***

**Comment by KaptainCS3** [comment]
!assign

**Comment by gbowne1** [comment]
@KaptainCS3 are you wishing to get assigned to this task?

**Comment by KaptainCS3** [comment]
yes

**Comment by gbowne1** [comment]
Ok.

**Comment by KaptainCS3** [comment]
Greetings sir I have an issue. I need the design to fully resolve the issue
and some of the code is not well structured. Can I restructure some?
I will patiently be waiting for the design.

**Comment by gbowne1** [comment]
@KaptainCS3 rough draft but.. Ignore the whitespace at the top...

![reactsocialmedia-Desktop - Main view](https://user-images.githubusercontent.com/47549872/216223139-691aa77b-a693-434b-9851-36e77e527e3d.jpg)

![reactsocialmedia-Copy of Page-1](https://user-images.githubusercontent.com/47549872/216223151-e270f62c-f8b6-4910-ac5d-7e0dff566ce6.jpg)

Will see if I can add the file...

**Comment by gbowne1** [comment]
This got fixed!! Closing this as complete.
