### ISSUE TITLE
[feature]: Make it possible for user to set a profile image url.

### ISSUE THREAD

**Issue by manuel12** [gbowne1/reactsocialnetwork#281]
### Is your feature request related to a problem? Please describe.

User should be able to set a profile image url on `/profile.` This  way each post could have a personalized image instead of having mine. 

### Describe the solution you would like

I will implement and add tests for this.

### Describe the alternatives you have tried

.

**Comment by gbowne1** [comment]
Unless we change it, /profile was intended to be a form for the new user to create their profile upon registering.  

If you want to use /profile to display the users profile, then I would suggest moving the form to a new route.  We could put form controls on the page that would allow the user to CRUD the user, like an edit profile button with an edit icon.  Then we wouldn't have to waste a route.

**Comment by manuel12** [comment]
> Unless we change it, /profile was intended to be a form for the new user to create their profile upon registering.
> 
> If you want to use /profile to display the users profile, then I would suggest moving the form to a new route. We could put form controls on the page that would allow the user to CRUD the user, like an edit profile button with an edit icon. Then we wouldn't have to waste a route.

Ok, we can make an edit-profile route, for example. I will try something like this.
