### ISSUE TITLE
[Bug]: change /src/index.js to .jsx and remove Strict Mode

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#287]
### Describe the Bug

I would like to propose we change /src/index.js to /src/index.jsx by doing this:

```jsx
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import reportWebVitals from "./reportWebVitals";
// import routes from "./routes";
import * as serviceWorker from "./serviceWorker";
// import 'bootstrap/dist/css/bootstrap.css';

ReactDOM.createRoot(document.getElementById("root")).render(<App />);
// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();

serviceWorker.unregister();
``` 

instead of 

```js
import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
```

### Steps to Reproduce

N/A

### Which device are you using?

Linux VM

### Which operating system are you using?

Linux x64, Debian 11 Base

### Which browser are you using?

Firefox 115

### Additional Context

This will also remove Strict Mode from the render methods.

### Contribute

- [ ] I am willing to contribute and submit a pull request

**Comment by Shiv-2712** [comment]
Hi, I am interested to work on this issue.

**Comment by gbowne1** [comment]
ok @Shiv-2712

**Comment by MihirRajChowdhury** [comment]
@Shiv-2712  are you still working on this issue I would like to contribute in this issue.

@gbowne1 If I do change the code according to specifications then index.css would not be able to render as it is not present in the new code will it be fine

**Comment by gbowne1** [comment]
Yes it needs to be changed as in the first post in this issue thread that I made.

In our app Strict mode is not necessary.  

Also make sure that in App.js the import for index.js is changed to .jsx
