### ISSUE TITLE
[Bug]: Issue with Local Storage utility

### ISSUE THREAD

**Issue by Piyush-Deshmukh** [gbowne1/reactsocialnetwork#289]
### Describe the Bug

~ **When we open the website in console it prompts :**

1. There is no "lastLoginCredentials" key in localStorage.
2. There is no "cookiesAccepted" key in localStorage.

~ **When the Cookies Modal pops console prompts :**

1. There is no "cookiesAccepted" key in localStorage.

~ **When we don't select any cookie preference by clicking anywhere on screen (to remove the Modal) console prompts :**

1. There is no "cookiesAccepted" key in localStorage.

~ **When we toggle modes (Dark/Light Mode) console prompts :**

1. There is no "lastLoginCredentials" key in localStorage.
2. There is no "cookiesAccepted" key in localStorage.

### Steps to Reproduce

1. Open Website.
2. Remove Cookie Modal by clicking anywhere on the screen.
3. Toggle modes (Dark/Light mode).

### Screenshots

![image](https://github.com/gbowne1/reactsocialnetwork/assets/99667276/43bb4e97-06d8-449d-8a4b-01d0c6daef99)

![image](https://github.com/gbowne1/reactsocialnetwork/assets/99667276/218bb815-a07f-4d28-a804-d6a431ebfa3d)

![image](https://github.com/gbowne1/reactsocialnetwork/assets/99667276/7101d388-57ec-4cec-88e0-c64700a7b89b)

### Which device are you using?

Windows Laptop

### Which operating system are you using?

Windows

### Which browser are you using?

Firefox

### Contribute

- [ ] I am willing to contribute and submit a pull request

**Comment by Tholkappiar** [comment]
**Hello Maintainers** , _Could you assign this issue to me !_

**Comment by gbowne1** [comment]
Sure @Tholkappiar, I will assign you now. thanks!

**Comment by gbowne1** [comment]
Just checking in, are you still working on this @Tholkappiar?

**Comment by Tholkappiar** [comment]
> Just checking in, are you still working on this @Tholkappiar?

Unfortunately, nope . Unassign me from this issue , I will try to make a PR if it is still open after some time !

**Comment by gbowne1** [comment]
ok thanks, just checking.  No worries at all. Let us know. thank you!
