### ISSUE TITLE
Terms & Conditions and Privacy Policy links

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#29]
**Describe the bug**
Terms and Conditions, Privacy Policy appear all jumblrd up at the bottom right of the view, almost not visiblr except that the text is white.

**To Reproduce**

Start the react dev server as per normal.

(Edit this)

**Expected behavior**

To be useable and visible this should be a part of the footer component, or made into something more accessible.  

I don't know much this will be accessed but I believe its legally required.

**Screenshots**

**Desktop (please complete the following information):**
   Linix, x64
   Firefox
 - Version 
   107

**Additional context**

**Comment by maciek04786** [comment]
Hi. I've managed to fix the issue by removing a couple of css properties from "NotFound.css". Removed "overflow" from display and fixed position of links. It's also showing all the components properly now. Can I be assigned to this, please?

![Screenshot 2023-02-01 174542](https://user-images.githubusercontent.com/105375946/216124659-a8793e01-07ca-4b9d-8108-1e1690244844.png)

**Comment by gbowne1** [comment]
Sure @maciek04786.  I can assign you.  Thanks.

**Comment by gbowne1** [comment]
It appears that recent commit/push/merge workflows have fixed this issue.
Closing this as done.
