### ISSUE TITLE
Contrast issues

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#3]
**Describe the bug**
[Accessibility]
 Contrast issues with the text [text leaf] which describes each panel component.  

**To Reproduce**

Run the dev server with npm start in the root dir. After the app loads in browser,
Press Ctrl Shift J or otherwise load the browser console // inspector.

1. Go to 'Accessiblity'
2. Click on 'All issues' button next to "Check for issues:"
3. See errors which include Contrast for the text which labels each panel 

**Expected behavior**

Fix this dark mode theme  to include good contrasting dark mode colors.  The current colors are/were meant for the dark mode.  Have not decided colors for light mode.

**Desktop (please complete the following information):**
   Linux, 64bit
   Firefox
   107

**Additional context**
This is an accessibility issue.

**Comment by Heini-Maria** [comment]
Hope your week has started well! 😊 Can I try and fix this, please?

**Comment by gbowne1** [comment]
Hi. Thank you.  Yes you can.  I will assign you.

**Comment by Heini-Maria** [comment]
Created a pull request #25 :) Let me know if you want any further changes to it. Cheers!

**Comment by gbowne1** [comment]
Looks great thanks for the PR.

**Comment by Heini-Maria** [comment]
Awesome thanks ☺️

**Comment by gbowne1** [comment]
I probably would've gone with just a slightly darker top navbar than the body.. there are still some minor contrast issues to work on still.
