### ISSUE TITLE
[feature]: Update profile UI according to the following wireframe.

### ISSUE THREAD

**Issue by manuel12** [gbowne1/reactsocialnetwork#302]
### Is your feature request related to a problem? Please describe.

The UI should be  updated following this wireframe:

![image](https://github.com/gbowne1/reactsocialnetwork/assets/4129325/0bb5d9e6-364a-43d1-b41a-18380f9a19ae)

The UI  should be very similar to the current wireframe  even if there might be more changes to some of the data in the future.

Also the current User model only consists of:

- Username
- Email
- Password
- Account Image Url

We can add mock data for the moment to feel out the other fields.

### Describe the solution you would like

Will implement design according to wireframe.

### Describe the alternatives you have tried

N/A

**Comment by lapso222** [comment]
hi,  could you assign me this issue or are you already working on this issue?

**Comment by gbowne1** [comment]
Here are some other things that could be added (captured from another issue & PR)

- Allow a user to upload a picture or upload/select an avatar (with possible drag and drop upload)
- Full Name including prefix and or suffix
- Display name / Username / Nick
- Location (current location, assuming USA.. City/Town, County, State, Zip but would need some internationalization)
- Age (hide/show toggle)
- Date of Birth (with toggle show/hide)
- Sex (Including non binary) (with hide/show toggle
- Ethnicity
- Marital Status (hide/show toggle)
- Political party afiliation (hide / show toggle)
- Education including schools and degrees and also include any school or career certifications.
- Occupation / Career
- list former workplaces 
- list current workplaces
- Places Lived
- Hometown (especially if different from current location)
- Map pin (Google Maps/Google Earth)
- Hobbies and Interests as tags
- Photo album (Gallery) could be cards 
- Banner photo/background
- Favorites (Color, Book(s), Movies, TV show, place, restaurant, food, etc)
- Date user joined
- View count (How many times profile was viewed)
- Number of Followers
- Ability to share profile with Share icon button
- Message and/or Chat 
- Follow button (does not add them as a friend, but allows the user to follow another users' feed)
- Follow count
- Like count
- Heart 
- Like / Thumbs Up / Thumbs Down
- Brief biography or About (150 words or less) Could be in the Details tabl.
- Tags for Hobbies and Interests. These are essentially hash tags people can follow various topics for discussion.

With the option to display or not display whatever information the user wants hidden from public view..

We also need a method for the user to pause/mute notifications, block, report users, admin/moderator to ban,

**Comment by gbowne1** [comment]
randomuser.me has a great API for mock data.

**Comment by manuel12** [comment]
@gbowne1 For the moment I will create an UI based on the wireframe and add fields like the ones shown in the wireframe. Later we can see if we can add more fields. But keep in mind that too many fields/data my clutter the UI making it hard for users to find what they are looking for.

**Comment by gbowne1** [comment]
thats why I suggested a tabbed UI inside the panel.

Replace things like Username with the actual data from the database.
