### ISSUE TITLE
[Bug]: Check and make sure all routes and endpoints are used.

### ISSUE THREAD

**Issue by manuel12** [gbowne1/reactsocialnetwork#321]
### Describe the Bug

As said by @gbowne1:

"We have a bunch of routes and endpoints that arent even in the UI or are wrong
Especially /dashboard and /admin as well as /profile and /user-profile"

I will check this routes and make sure they are working properly.

### Steps to Reproduce

Check the following routes:

-  /dashboard
- /admin
- /profile
- /user-profile

Make sure they are used properly.

### Which device are you using?

Asus VivoBook

### Which operating system are you using?

Windows

### Which browser are you using?

Chrome

### Contribute

- [x] I am willing to contribute and submit a pull request

**Comment by gbowne1** [comment]
@manuel12 

We should also document all of the routes and/or endpoints, as well as screenshots of what they look like if they are actual pages in the app.  I have lost track of them.
