### ISSUE TITLE
[feature]: Use Twitter, OpenGraph, etc meta tags 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#336]
### Is your feature request related to a problem? Please describe.

Twitter/X, and OpenGraph provides social meta tags for use in the header section of apps and websites.

It might be handy to use some in our app.

### Describe the solution you would like

Ideas?

### Describe the alternatives you have tried

Idk if there is any alternative

**Comment by gbowne1** [comment]
Some searching reveals Linkedin and Pinterest  also use OpenGraph tags.

**Comment by dev-george-nikolaidis** [comment]
Hi @gbowne1  ,we can create a CustomSeo component that will include OpenGraph and other meta tags related to the app and receive special parameters for each page. In essence, we can use this CustomSeo component on every page. Like this, we can have a great useable component. How does it sound to you?

**Comment by gbowne1** [comment]
@dev-george-nikolaidis 

I only understood that the meta tags need to go into the index.html in public.

If it needs a custom component, that would be fine with me.

There will be a analytics page that needs created.

**Comment by dev-george-nikolaidis** [comment]
Creating 'CustomSeo' allows you to include it on every page and have more control if you want to add more parameters, for example, the page title, than the standard, and whatever else you want. When the page component mounts in the 'root div' inside the index.html body, it will update the meta tags of the current component, but this approach requires the React Helmet async library to achieve SSR for SEO. The other approach, as you suggest, is to hard-code the meta tags we want directly in index.html and maybe go from there on how we can improve them.

**Comment by gbowne1** [comment]
helmet is installed on the server I think.

Yes, We can always start simple. Its a great idea either way.

Ive never used SEO in React before and am very interested to see how it turns out.

Lighthouse / Pagespeed scores really need to be tested again.
