### ISSUE TITLE
[Bug]: login button

### ISSUE THREAD

**Issue by akshayamadhuri** [gbowne1/reactsocialnetwork#352]
### Describe the Bug

After clicking on login button it's not reaching to correct URL

### Steps to Reproduce

click on login button

### Screenshots

![Screenshot (162)](https://github.com/gbowne1/reactsocialnetwork/assets/76612327/27f51e51-bca4-4574-8d48-114cc72eabc1)

### Which device are you using?

lenovo

### Which operating system are you using?

windows

### Which browser are you using?

chrome

### Contribute

- [ ] I am willing to contribute and submit a pull request

**Comment by dev-george-nikolaidis** [comment]
Hi @gbowne1, can I work on this task?
