### ISSUE TITLE
[Bug]: Unable to access web page

### ISSUE THREAD

**Issue by akshayamadhuri** [gbowne1/reactsocialnetwork#398]
### Describe the Bug

unable to access port 3000 showing 
![Screenshot (272)](https://github.com/user-attachments/assets/835383ee-888a-4120-83a1-5a8b3d356657)

### Steps to Reproduce

1.Go to cd /client
2. npm start

### Which device are you using?

lenovo

### Which operating system are you using?

windows

### Which browser are you using?

chrome

### Contribute

- [ ] I am willing to contribute and submit a pull request

**Comment by akshayamadhuri** [comment]
@gbowne1

**Comment by gbowne1** [comment]
@akshayamadhuri 

Theres not much information for us to go on here.  Unless you can provide us all of the steps you went through to get this far, we can not fix this bug if it is one, and I have not been able to reproduce this as it does work.

Need more information as to how you got to this point.

Simply going to the client folder/directory and doing `npm start` won't work.

Did you install the packages from client and the server?

Thanks
