### ISSUE TITLE
[CSS] Build Theme for light and dark mode

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#4]
**Describe the bug**
[Theme]
 
- [Done] Fix theme switch toggle [in nav bar next to user icon] or allow users default theme.

Current theme coloring is dark mode.

Edit: 
  Dark Mode Colors:
     Black, Gray, White

  Light Mode Colors:
     Blue?? White??
   
   

**To Reproduce**

Run the dev server with npm start in the root dir. After the app loads in browser,
Press Ctrl Shift J or otherwise load the browser console.

1. Go to 'Accessiblity' tab
2. Click on 'All issues' button next to "Check for issues:"
3. See errors which include Keyboard, Contrast and Text-leaf for the icons in the navbar and the 

**Expected behavior**

Good color theme for dark and light mode which meets WCAG.  

**Desktop (please complete the following information):**
   Linux, 64bit
   Firefox
   107

**Additional context**
This is an accessibility and themeing issue.

**Comment by gbowne1** [comment]
@UjjawalTyagi123 fixed the theme switch. So now work can be done building a theme.

**Comment by UjjawalTyagi123** [comment]
what kind of theme would you like to be build.

**Comment by UjjawalTyagi123** [comment]
plzz explain in detail

**Comment by gbowne1** [comment]
More of the components will have to be completed and colors chosen, but my first idea is black, white, gray should be dark mode theme and some colors for light mode.  

I usually like to use a theme.js like with styled-components, but: 
https://css-tricks.com/theming-and-theme-switching-with-react-and-styled-components/

**Comment by UjjawalTyagi123** [comment]
I think we have to First focus on building components then we would move on building proper theme that makes sense I think.

**Comment by gbowne1** [comment]
My focus is 100% on working vs. looking good. Colors can definitely be chosen later on.

**Comment by gbowne1** [comment]
I think this is slowly coming  together as far as theme, etc. so closing this.
