### ISSUE TITLE
[CSS] Fix the Settings.jsx component 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#40]
Describe the bug
There are several things wrong with the Settings.jsx component, which include contrast ratio problems for accessiblity.

These are the `<h3>`'s and the `<div>`s for the section container.

To Reproduce

Run the dev server with `npm start` in the root dir. May need to `npm i` or `npm install` the app as I did not include my local node_modules dir. in the upload and it is in the .gitignore.

Expected behavior
Screen reader accessibility

Desktop (please complete the following information):

    Linux, x64
    Firefox, Chrome
    both 107

Additional context

**Comment by pawel975** [comment]
I can work on it @gbowne1

**Comment by gbowne1** [comment]
Ok @pawel975 thank you!

**Comment by gbowne1** [comment]
See also Issue #53
