### ISSUE TITLE
[CSS] Fix the width of the components/panels

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#43]
**Describe the bug**

Fix the width of the components in the view.  Components like Dashboard, Settings, etc. should be 1400-1500px wide maximum in a 1920x1080 (or my viewport at 1880x900) leaving room for 200-250px left sidebar (with Groups, Events, etc. buttons) and 200-250px right sidebar and some small margin between

**To Reproduce**

Run the dev server with `npm start` in the root dir. May need to `npm i` or `npm install `the app as I did not include my local node_modules dir. in the upload and it is in  the .gitignore.

**Expected behavior**

**Desktop (please complete the following information):**
   Linux, x64
   Firefox, Chrome
   both 107

**Additional context**

There are also issues with the components  themselves which include a whitespace on the right side of each component panel.  There should be no whitespace.

**Comment by manuel12** [comment]
Hi :) I have an idea on how to solve this issue, could I have it assigned to me?

**Comment by gbowne1** [comment]
Ok @manuel12 I will assign you
