### ISSUE TITLE
Logo must be an image placeholder, is currently text.

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#44]
**Describe the bug**
[App]
[TODO] 

We do not have a logo yet or a good name for this application, so the logo must be a image placeholder not text.  The logo currently appears in the top nav/top bar as text.

Add an image placeholder, till an appropriate logo for the app can be chosen.  Possibly use the included logo .png files until that time.

**To Reproduce**

Run the dev server with `npm start` in the root dir. May need to `npm i` or `npm install` the app as I did not include my local node_modules dir. in the upload and it is in the .gitignore.

**Expected behavior**
Add an image placeholder to the top nav/top bar and remove the text logo. 

**Desktop (please complete the following information):**
   Linux, 64bit
   Firefox, Chrome
   both 107
**Additional context**
This may be a part of another reported issue and may need some work before other issues are or can be completed.
Some routes may need a protected route and may need a login function completed before redirecting/routing.

**Comment by Parth1125** [comment]
Hi @gbowne1  please assign me this issue i have figured it out I will solve it
