### ISSUE TITLE
Add a hamburger menu and/or close icon/button to close the left side panel / left side nav

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#46]
**Describe the bug**
I fixed the view to show the 250px wide left side panel / side navigation which should have buttons.  

There is no way to open or close this panel with a

These buttons should be:
Groups (Routes to /groups)
Events (routes to /events with an events component comprised of a calendar and list of events and means of creating events)
Messages (routes to /messages/
Friends (routes to /friends with the Friends component composed of cards, and also showing friends request as cards)

**To Reproduce**

Run the dev server with `npm start` in the root dir. May need to `npm i` or `npm install` the app as I did not include my local node_modules dir. in the upload and it is in the .gitignore.

**Expected behavior**

A method to close/open the left side nav / side panel and menu with icons, completed routing as above.

**Desktop (please complete the following information):**
   Linux
   Firefox, Chrome
   both 107

**Additional context**
This issue may need to be completed before some other issues can be worked on.

**Comment by kp30-bit** [comment]
I'll take this up.

**Comment by gbowne1** [comment]
Ok, feel free to contribute.  I will assign you to this task.  Thanks.

**Comment by gbowne1** [comment]
@kp30-bit How close are you to having something to PR?
