### ISSUE TITLE
[CSS] Fix Footer component

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#51]
**Describe the bug**
The footer needs the styling to normalize the colorization, etc.

**To Reproduce**

May need to install with `npm i` or `npm install` as I did not include my local `node_modules` folder in the initial commit.

Start the dev server by running `npm start` in the root of the project.  Browser will start in localhost.
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
   Firefox, Chrome
  Both 107

**Additional context**

**Comment by Abhishek7Tech** [comment]
Hi @gbowne1 I would like to contribute!

**Comment by gbowne1** [comment]
Ok, feel free to contribute.  I will assign you to this task.  Thanks.

**Comment by Abhishek7Tech** [comment]
@gbowne1 working on it!

**Comment by gbowne1** [comment]
Ok. @Abhishek7Tech

**Comment by gbowne1** [comment]
So the footer component is made up of an:

- section.Footer-footer
- ul which on my view is 1884x36 in the middle of that and its a flex container.
- a and li in the ul which have really weird sizing if you look in the inspector and hover over the element (at least in Firefox)

The footer appears to be black, then a gray then a light gray.  

Not sure how it would look best in a dark mode theme.

The links are too far apart as well and there is no copyright info on the page.

**Comment by gbowne1** [comment]
This is the current transition for the footer from dark to the gray footer.  there's something else in there and not sure what it is.  Inspecting it doesnt seem to reveal a whole lot except in the last comment.

![Screenshot 2023-02-24 at 15-00-59 React Social Media App](https://user-images.githubusercontent.com/47549872/221316772-34555ce2-e2fd-4954-a300-b91055a55d22.png)
