### ISSUE TITLE
[TODO] Add method to accept cookies

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#54]
**Is your feature request related to a problem? Please describe.**

The app needs a flow for the user to accept cookies due to the cookie law.

**Describe the solution you'd like**
A popper, toast, modal, etc. to accept cookies.

**Describe alternatives you've considered**

**Additional context**

**Comment by gbowne1** [comment]
Something like this

<img width="626" alt="633ee1dd8497c1b74fedae7e_compliant-cookie" src="https://user-images.githubusercontent.com/47549872/222056578-1007b4b3-f507-49c0-9e5e-8672cfad3127.png">

**Comment by gbowne1** [comment]
We will need to comply with GDPR in order to be used in the EU.

**Comment by gbowne1** [comment]
I can see you wanted to work on multiple issues.  

Youre welcome to work on any issue.  

We have not decided where this component will actually go yet, but it will need to display when you start the app.

@pawel975 @manuel12

**Comment by goutham03062001** [comment]
Yeah definetly I'll work upon it.

You just need that modal...? I mean What content I've put. Like how we are utilizing their data and what we are doing with that. We have to mention all of that  right? And should i make a prompt exactly like that? or shall i work upon my own design
