### ISSUE TITLE
[TODO] Complete Post.jsx component

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#58]
**Is your feature request related to a problem?**
 No.

**Please describe.**

**Describe the solution you'd like**
A Post.jsx component with associated CSS component that has a text input field like the one Facebook uses that says something like "Whats on your mind?".

**Describe alternatives you've considered**
Ability to add photos, videos, delayed posting. Include minimal edit text controls.  Upload controls.

**Additional context**

**Comment by gbowne1** [comment]
Here are some examples to use as inspiration.

![Screenshot 2023-02-17 at 15-31-42 Home _ Twitter](https://user-images.githubusercontent.com/47549872/219816456-51a20036-557e-4b99-8e60-30a8c02cba99.png)

![Screenshot 2023-02-17 at 15-31-04 (99 ) Feed LinkedIn](https://user-images.githubusercontent.com/47549872/219816462-53baa2cd-8240-491d-ad8f-07dd411ef08e.png)

![Screenshot 2023-02-17 at 15-27-15 Facebook](https://user-images.githubusercontent.com/47549872/219816464-99e489eb-039d-4759-bf21-8d8af22754d8.png)

**Comment by pawel975** [comment]
@gbowne1 I can work on that feature, you can assing me.

**Comment by gbowne1** [comment]
Ok @pawel975
