### ISSUE TITLE
[TODO] Add Express and Node server and nodemon

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#59]
**Describe the bug**

This app would probably be best as a seperated client and server with express, node and nodemon. So that you have to start the server first then connect the client snd database.

They are already installed.

Add a seperate src/server tree with its own package.json and build a express and node server, monitored wih nodemon.

**Expected behavior**

**Additional context**
Not sure if this is how it is with full stack apps.

**Comment by TechLateef** [comment]
i see that you already have a folder called src in the repo

**Comment by gbowne1** [comment]
@TechLateef 

I have seen other projects where it is either /src/client/ & /src/server/ or /client/src/ & /server/src/...

**Comment by TechLateef** [comment]
the last option will be great    are you done with the backend ?? and how can i contact you i try via twitter but its like you dont allow message

**Comment by gbowne1** [comment]
I figured it might be.  

I have twitter messages turned off.  If you need to contact me about this project you can do so in the Discussions tab.

The backend is not even started yet.

Doesnt make sense yet till the Frontend is more complete.
