### ISSUE TITLE
Search field and it's icon not styled correctly

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#6]
**Describe the bug**
[App]
 
  Fix the search field and icon in the nav bar including it's label.  Ideally this field should only be used to search the site itself.  The label is to near the left edge of the field.
 
**To Reproduce**

Run the dev server with npm start in the root dir.  May need to install using `npm i` or `npm install`.  I did not include my local node_modules dir in the upload.

**Expected behavior**

Correctly styled icon and field.  This field seems a bit long.  I would suggest limiting this to a more compact size.  

**Desktop (please complete the following information):**
   Linux, 64bit
   Firefox
   107

**Additional context**

**Comment by elmehdi1212** [comment]
Can I help you with this issue?

**Comment by gbowne1** [comment]
yes @elmehdi1212 I can assign you.

**Comment by elmehdi1212** [comment]
![Capture](https://user-images.githubusercontent.com/62912924/213878816-d1234e62-b03b-4b42-bef1-46308eab89cf.PNG)
how about this size ?

**Comment by gbowne1** [comment]
@elmehdi1212 that size is fine.

**Comment by elmehdi1212** [comment]
is there anything to add ?

**Comment by gbowne1** [comment]
@elmehdi1212  Nothing to add at this point.  The search icon isn't as good as it could be.  I hadn't decided on placement
of the magnifying glass Search icon.  This could be a bit better, leaving the search field to either be centered or to the left of the top bar.

The majority of the icons will be a part of the User Icon.

**Comment by elmehdi1212** [comment]
![Capture](https://user-images.githubusercontent.com/62912924/213945573-24993efb-643e-4e32-b558-4bad38bd5c11.PNG)
@gbowne1  Do you want something like this  ?

**Comment by gbowne1** [comment]
@elmehdi1212  Yeah that was more like my original idea.

**Comment by elmehdi1212** [comment]
![image](https://user-images.githubusercontent.com/62912924/213947858-f990a66b-85ed-48cc-a38a-b8f0908583d8.png)
@gbowne1  now is that ok for you ?

**Comment by gbowne1** [comment]
@elmehdi1212 Other than color, sure.

**Comment by elmehdi1212** [comment]
@gbowne1 which color do you want ?

**Comment by gbowne1** [comment]
@elmehdi1212 

My first thought would be the same gray as in the header of one of the panels, as in where it says "Userprofile".

**Comment by elmehdi1212** [comment]
![image](https://user-images.githubusercontent.com/62912924/213949547-dc6bf024-50f8-41be-a2de-bd7f11b8336e.png)
@gbowne1  like this ?

**Comment by gbowne1** [comment]
yes

**Comment by elmehdi1212** [comment]
@gbowne1  now I can make a pull request ?

**Comment by gbowne1** [comment]
Sure.. PR's always welcome.

**Comment by gbowne1** [comment]
@elmehdi1212 let me know when youre able to PR.

**Comment by elmehdi1212** [comment]
@gbowne1  I made a PR

**Comment by gbowne1** [comment]
Thanks @elmehdi1212 for the PR..  I made those changes locally and tested them out.  It works fine.  I have merged your changes.
