### ISSUE TITLE
[TODO] Add Material UI Icons to SideNav component

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#60]
**Describe the bug**

There are no Material UI icons next to the buttons on the SideNav component.

**Expected behavior**
There should be appropriate Material UI icons on SideNav component 

**Desktop (please complete the following information):**
   Linux, x64
   Firefox, Chrome
   107 or newer
**Additional context**

**Comment by Dylan-Clarry** [comment]
Hi @gbowne1 ! I'm looking to get started in working on open source projects and know some React. Mind if I work on this problem?

**Comment by gbowne1** [comment]
Sure @Dylan-Clarry go ahead. I will assign you.  Thank you :+1:

**Comment by Dylan-Clarry** [comment]
NP! I'll probably get to this in the morning and keep you updated.

**Comment by gbowne1** [comment]
@Dylan-Clarry No worries.  Thanks for letting me know.  If it gets beyond a few days or need anything that may help, let me know.  Screenshots of working changes when you PR.  Thank you.

Am going to be adding a document for devs (setup, etc.) soon.

**Comment by Dylan-Clarry** [comment]
Sounds good!

**Comment by Dylan-Clarry** [comment]
![screen_19-25-02](https://user-images.githubusercontent.com/26127235/220217898-8a031ff7-9893-4246-ade7-bf6f676c9ef6.png)
@gbowne1 is this what you had in mind?

I made sure to use MUI icons and used a transform scale so it scales with the text at different screen sizes.

**Comment by gbowne1** [comment]
Yes that is it 100%.  Looks great! Thanks! :+1:

**Comment by Dylan-Clarry** [comment]
Awesome! I'll make a PR

**Comment by gbowne1** [comment]
@Dylan-Clarry feel free to work on anything else you would like to.  A lot of the UI needs to be moved to Material UI components.
