### ISSUE TITLE
[CSS] TopBar/TopNav not sticky when scrolling

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#61]
**Describe the bug**
The Topbar/TopNav is not sticky when the SideNav is open.  It only appears to be sticky when the SideNav is closed and even then the scrolling is a bit wierd, but works.

**To Reproduce**

Run the dev server with `npm start` in the root dir. May need to `npm i` or `npm install` the app as I did not include my local node_modules dir. in the upload and it is in the .gitignore.

**Expected behavior**

Smooth scrolling and sticky top bar / top nav.

**Desktop (please complete the following information):**

**Additional context**
Consider moving more components to using Material UI's componentry, like AppBar, etc.

**Comment by thiyagarajan17** [comment]
please assign the issue.. would love to work on it!
