### ISSUE TITLE
[BUG] Friends.jsx:  Color in Typogography

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#66]
**Describe the bug**

`Expected color but found ‘text’.  Error in parsing value for ‘color’.  Declaration dropped.`

coming from line number 44 of Friends.jsx as `color="text.[primary]"`

**To Reproduce**

**Expected behavior**
Fix the Material UI Typography, possibly by removing the color value.

**Desktop (please complete the following information):**
  Linux, x64
  Firefox, Chrome
  107

**Additional context**

**Comment by pawel975** [comment]
Hello, I would like to work on that issue, could you assign me?

**Comment by gbowne1** [comment]
Ok @pawel975
