### ISSUE TITLE
[TODO] Move TopBar/TopNav to use Material UI 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#72]
**Is your feature request related to a problem?**
No.

**Please describe.**

Move the TopBar/TopNav to use Material UI <AppBar>

https://mui.com/material-ui/react-app-bar/

**Describe the solution you'd like**

Desktop view should have a 40-65px topbar with (L to R)

- Hamburger to open `<Drawer>` from left
- Logo
- Search field with the MUI v5 `<SearchIcon>`
- Envelope Icon for Messages
- Material UI `<MessageIcon>` for Messages
- Material UI `<ChatIcon>` for Chat 
- Material UI '<NotificationsIcon>` for Notifications
- Materail UI `<AccountCircleIcon>` (with state change from login/logout) (Note: this needs a dropdown menu)
- Material UI ToggleOn and ToggleOff Icon with state change for theme switch

**Describe alternatives you've considered**

Login/Logout, Settings, Help Icons all go in the AccountCircleIcon dropdown menu  

Mobile view is currently a mess and for a later design revision and issue.

**Additional context**
AccountCircleIcon dropdown menu is a seperate issue I made

@Dylan-Clarry

**Comment by gbowne1** [comment]
This one is not letting me assign till user comments.

**Comment by Dylan-Clarry** [comment]
Sorry didn't realize that's how it worked, commenting now

**Comment by gbowne1** [comment]
Yeah it wont let me assign till you comment on the PR, unless you are assigned a collaborator role in Settings.

**Comment by pawel975** [comment]
@gbowne1 you can assign me

**Comment by gbowne1** [comment]
Ok assigned

**Comment by gbowne1** [comment]
@pawel975 did you mean to close this?

**Comment by pawel975** [comment]
> @pawel975 did you mean to close this?

Yeah, I upgrade that top nav and since I'm collaborator I directly pushed to main and closed issue, sorry if I shouldn't do that.

**Comment by gbowne1** [comment]
Yes its ok.  @pawel975 

As contributor you have direct push access but you should still do a PR so we can review your PR unless the commit(s) are non breaking changes just to keep the tree clean.  I still would like to be able to review as much as possible.  This will be important the more contributors we get.

Youve made enough commits, PRs and merges that I felt it wise to give you comtributor access.

I really need to update the PR guidelines...  thanks so much for your contributions amd feel free to review PRs as time permits.

**Comment by pawel975** [comment]
> Yes its ok.  @pawel975 
> 
> As contributor you have direct push access but you should still do a PR so we can review your PR unless the commit(s) are non breaking changes just to keep the tree clean.  I still would like to be able to review as much as possible.  This will be important the more contributors we get.
> 
> Youve made enough commits, PRs and merges that I felt it wise to give you comtributor access.
> 
> I really need to update the PR guidelines...  thanks so much for your contributions amd feel free to review PRs as time permits.

Sure, I was surprised because I thought even if I push it, it will demand PR too. I will figure out how to do PR next time 😀

**Comment by gbowne1** [comment]
I will be giving Contributor access to anyone doing significant work helping the project out.  Its the least I could do.  Normally I would wait for a few more commits, PRs, merges.. but you already did a lot of work it made sense to do that now.

**Comment by pawel975** [comment]
> I will be giving Contributor access to anyone doing significant work helping the project out.  Its the least I could do.  Normally I would wait for a few more commits, PRs, merges.. but you already did a lot of work it made sense to do that now.

Sure, I'm glad to contribute 😀

**Comment by gbowne1** [comment]
I always welcome contributors and always will.   In this case it was ok to push because the feature was already there, just needed enhancing features by adding MUI.

I will make sure that contrubutors especially major contributors get mentioned in releases.  Thanks muchly
