### ISSUE TITLE
[TODO] Move the SideBar // SideNav to use Material UI <Drawer>

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#73]
**Is your feature request related to a problem?**
No.

**Please describe.**

Move the SideBar // SideNav to use Material UI <Drawer>

https://mui.com/material-ui/react-drawer/

**Describe the solution you'd like**

Desktop view this should be 200px-250px wide 

The colorization/background, etc. of this should change state with the theme switch.

The components Groups, Events, Friends should render to the center column when the user clicks on the button.  

**Describe alternatives you've considered**

Mobile view is currently a mess and for a later design revision and issue.

**Additional context**

@Dylan-Clarry

**Comment by pawel975** [comment]
I could try it, you can assign me @gbowne1

**Comment by gbowne1** [comment]
@Dylan-Clarry said he wss going to work on that today.  Perhaps you could collaborate a little.

I could not find any images for some inspiration but Facebook tends to have good layout && design so I would loosely follow that @pawel975 

Comment if you can @Dylan-Clarry

**Comment by Dylan-Clarry** [comment]
Hi! Yes I'm open to working on this together, or you could also give @pawel975 issue [#72](https://github.com/gbowne1/reactsocialnetwork/issues/72) since it's a similar problem

**Comment by gbowne1** [comment]
Sure @Dylan-Clarry I can do that

**Comment by gbowne1** [comment]
I am open to have people work on issues together.

**Comment by pawel975** [comment]
@gbowne1 @Dylan-Clarry 
Since side bar and top bar are similar maybe I'll just focus on top bar and @Dylan-Clarry on side bar?

**Comment by gbowne1** [comment]
Either one you would like to do. @pawel975 

If anyone wants to collaborate on any issue, thats fine. At least to share some ideas.  

Someone could break up the task to UI/UX / Front end and backend.  Or even break up the frontend task where someone writes the code for a component the other does the CSS, etc. 

Always appreciate any ideas for teamwork collab or anything as a discussion in Discussion tab.  

I will make a dev guide tomorrow.

**Comment by pawel975** [comment]
Ok @gbowne1 thanks you can assign me to issue #72

**Comment by gbowne1** [comment]
Ok @pawel975 For me to do that you need to go comment over on the issue (or any other issue you would like to work on).  Then it will let me add you.

**Comment by gbowne1** [comment]
Closed this as largely complete with recent merges.
