### ISSUE TITLE
[TODO] Enhance the Events component

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#77]
**Is your feature request related to a problem?**

**Describe the solution you'd like**
Complete and or create the Events compoment as JSX

Use Material UI v5 for icons etc

Provide a method facility for CRUD operations to events.  This ideally should have a calendar.

Also some facility for displaying events as cards with name of the event, its date and time and location and  possibly a google maps pin.

This component should open in the middle column  of the view when clicking on the Events button in the SideNav drawer.

**Describe alternatives you've considered**

**Additional context**

**Comment by gbowne1** [comment]
I am going to try working on this for the next few days while I am waiting on other things.  If not, I'll get started on it and commit and PR what I have so far.  We have quite a few components to complete and most of them are empty

Open to ideas here.

I was looking for things that might help here.  

@manuel12 @pawel975 @Dylan-Clarry

**Comment by manuel12** [comment]
I can try to implement a component like this for starters:

![image](https://user-images.githubusercontent.com/4129325/223232559-29af5fd6-3ce8-4b2f-b30b-64752710296b.png)

**Comment by gbowne1** [comment]
@manuel12 

 I actually like the look of that inside the component panel.. and it needs some panel to create the events either a personal event or a group event.. and possibly others as time goes on.

**Comment by manuel12** [comment]
That's true. Will add some UI also for this functionality.

**Comment by gbowne1** [comment]
Oh and making it a public or private event.

**Comment by manuel12** [comment]
I will implement the component UI as in the wireframe for now. Then on subsequent ticket I will add further UI/functionality. This way we don't end up with one massive PR that changes a bunch of files and introduces a bunch of things and would take a while to get reviewed. 

I will create further tickets breaking this tasks down into parts and assign them to me.

**Comment by gbowne1** [comment]
Fine with me.  I do not know how anyone else feels about this but I am ok reviewing whatever.  Making it managable is good though. 

Testing things out in any iteration here will be key especially the larger the project gets.   I also say the moment we have enough components in the UI we should look at testing.

Hoping also we can get a couple of others on board too.

**Comment by gbowne1** [comment]
We already have a whole pile of issues, most bordering on stale.. go easy on the issues at first unless you see bugs or missing things.  In a weeks time I'd like to see a number of them reduced.  Most of the current ones are component related.  Don't be afraid to use the discussions tab to hash out some ideas.

**Comment by gbowne1** [comment]
Some more inspiration for enhancing this component

![Screenshot 2023-03-14 at 12-40-02 Events Near Me Facebook](https://user-images.githubusercontent.com/47549872/225118705-e23ac9be-c172-41c0-a18f-75e1f3de6bb0.png)

**Comment by gbowne1** [comment]
Merging the PR should improve the Events workflow.  This should be good as we work towards 1.0

**Comment by gbowne1** [comment]
This is largely complete with the merging of the last PR. #145
