### ISSUE TITLE
[TODO] App should have single source of colors and fonts.

### ISSUE THREAD

**Issue by pawel975** [gbowne1/reactsocialnetwork#88]
**Is your feature request related to a problem? Please describe.**

I think single source of colors and fonts would simplify styling, coping variables between components  is tiring and would be painful if we would change overall styling.

**Describe the solution you'd like**

We can combine CSS for overall styling and MUI system for creating theme and injecting colors & font directly to elements in .jsx files.

**Describe alternatives you've considered**

We could switch from CSS to SCSS, it would enable to create file with all colors & fonts and import it to each SCSS file so it can get access to those variables. Big downside of this solution is switching between themes, I tried to that in few projects but failed each time.

**Comment by gbowne1** [comment]
I totally agree @pawel975 

We really need to build out an accessible theme contoller. Theme.js which controls everything about the themes. 

I am not that imterested in SCSS just yet anyhow.  I have not had any success with it.   I mean its fine but I dont know how I couls maintain it.   I personally am better off with plain CSS.  I can read and debug it by sight.

**Comment by gbowne1** [comment]
I also want to make people working on themes and CSS aware of this:

https://www.w3.org/WAI/older-users/
https://www.w3.org/WAI/older-users/literature/

**Comment by pawel975** [comment]
> I totally agree @pawel975 
> 
> We really need to build out an (user) accessible theme contoller. Theme.js which controls everything about the themes. I've seen it done but can't remember how..  
> 
> Edit:  MUI has some great, excellent, wonderful things for theme and styling.  
> 
> I am not that imterested in SCSS just yet anyhow.  I have not had any success with it.   I mean its fine but I dont know how I could maintain it let alone ensure someone else could.   I personally am better off with plain CSS.  I can read and debug it by sight.  If we change to SCSS, SASS, LESS, etc..  someone is going to have to try maintaining it and converting what we have.  I have a distinct feeling that more people know CSS than any of the SASS types.  (as a side note MUI, FontAwesome, Bootstrap all emit SASS  types from the CDN  by default so there is that...).

Sure, I will follow MUI system and stay with CSS with that

**Comment by gbowne1** [comment]
Ok @pawel975 

I am sure whatever we come up with will work fine.

It is starting to come together. Now to work on completing components.  I was going to try working on adding some stuff today while I have time at the PC.

**Comment by gbowne1** [comment]
I added a fonts issue

**Comment by pawel975** [comment]
I have an idea. We can use html objects only if needed (for instance as a containers) and in other situations use MUI elements. It would simplify styling because we cant override default MUI elements [styling](https://mui.com/material-ui/customization/default-theme/) in createTheme() function. It will apply styling for whole app including fonts colors etc. I can migrate all components according to this sollution but I would like to know if I should. @gbowne1

**Comment by gbowne1** [comment]
Yeah I think thats a great idea @pawel975.  Theres a number of ways we could go about theming and fonts.

If we had more contributors I would put it to a vote.

I think whatever solution we choose we should be consistent with.  

Im glad that the App is working so much better than it was.

Thoughts @manuel12 @pawel975 @Dylan-Clarry et al

**Comment by pawel975** [comment]
I change my mind, styling only with MUI is very hard and not so flexible. Besides would be problematic for new contributors since every front dev knows plain CSS but not necessarily MUI. I could create variables.css file which contains variables colors for background, text etc for both dark and light mode and every CSS file would import those variables and use it. I tested it and it works, i thought that only SCSS allows for variables imports.

**Comment by gbowne1** [comment]
@pawel975 

That is what I was thinking too.  We can continue doing what we have been doing.  It's not a big deal.  I like the idea of CSS variables though.  Keep in mind this: (<https://mui.com/material-ui/customization/theming/>)

I had the same problem with my other app I am working on which is MERN/PERN (https://github.com/gbowne1/SPMS_ERP_MRPUpdatedRepo).. its in a complete mess as well.  At that point MUI was new to me.
