### ISSUE TITLE
Add icons and more items to MUI User Icon/Avatar dropdown

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#89]
**Is your feature request related to a problem? Please describe.**

The new User Icon/Avatar Icon has also a new dropdown menu.  It needs more items and icons to go with them.

- Settings (with SettingsIcon )
  Opens the Settings.jsx component in the main view? or a modal?
  route: /settings/  i.e. /settings/notifications/
  route: /help

- Help (with HelpIcon) 
  Opens the Help.jsx component somewhere
  Another modal?
  route: /help
  
- Feedback (with FeedbackIcon)
  Possibly a modal 
  Not sure where to put this in the UI
  route: ??

- Logout / Login needs a state change in the menu (with toggle??)
  Login/Logout Modal 
  Register if the user is not registered yet (this component not built or rendered yet.)

- (Optional) Change 'My acccount' to User Account or Profile or User Profile or a state to show user name?? 
  Clicking this should open the UserProfile (UserProfile.jsx) or Profile (Profile.jsx) component in the main view.  You know, naming      things is hard.

**Describe the solution you'd like**
Some form of the solution from above.

**Describe alternatives you've considered**
Looked at the UI/UX from Facebook (desktop view) for some inspiration. These just change the menu or the right sidebar/sidenav completely in their UI/UX.  (don't have access to many others and there were not many sandboxes with good ideas here especially with the react context)

**Additional context**
Make the most efficient use of API's and Hooks and Context and various states.  The more the merrier.

@manuel12 @pawel975 @Dylan-Clarry , etc.

**Comment by gbowne1** [comment]
This is somewhat complete

**Comment by manuel12** [comment]
I would like to work on this. Please assign me.

**Comment by manuel12** [comment]
> This is somewhat complete

I can add the Settings, Help and Feedback Menu items, icons and routes.

**Comment by gbowne1** [comment]
@manuel12 that looks great.  Do a PR and will review it
