### ISSUE TITLE
SideNav component can be placed outside the routes

### ISSUE THREAD

**Issue by manuel12** [gbowne1/reactsocialnetwork#91]
**Is your feature request related to a problem? Please describe.**
Right now the SideNav component is one of  the routes, like so:
```
        <div className="Main-app-container">
          <Router>
            <Routes>
              <Route exact path="/settings" element={<Settings />} />
              <Route exact path="/profile" element={<UserProfile />} />
              <Route exact path="/dashboard" element={<Dashboard />} />
              <Route exact path="/terms" element={<NotFound />} />
              <Route path="*" element={<SideNav isSideNavVisible={isSideNavVisible} />} />
```

The reason it occupies the "*" routes is so that it appear on all routes. This definetely what we want but we can achieve this in a simple way.

**Describe the solution you'd like**
By placing the SideNav element before the Router like so:
```
        <div className="Main-app-container">
          <SideNav isSideNavVisible={isSideNavVisible} />
          <Router>
```

This way we can achieve the same effect. Also this way we leave the "*" route for the NotFound component.

**Comment by manuel12** [comment]
@gbowne1 I would like this assigned to me please :)

**Comment by gbowne1** [comment]
@manuel12 ok.. Make sure if you are using the GitHub interface.. that issues are added like that ^^ whenever you create an issue.

"Senior Social Dating Site" is the project (visible in the Project tab)
Frontend (UI/UX) is the milestone and whatever labels you need.  Can create a labels.yml for better labeling in one of the .github folders, unless of course its a backend task.

**Comment by manuel12** [comment]
> @manuel12 ok.. Make sure if you are using the GitHub interface.. that issues are added like that ^^ whenever you create an issue.
> 
> "Senior Social Dating Site" is the project (visible in the Project tab) Frontend (UI/UX) is the milestone and whatever labels you need. Can create a labels.yml for better labeling in one of the .github folders, unless of course its a backend task.

Will do. Thx for the info :)

**Comment by gbowne1** [comment]
You're welcome.. this helps out GitHub with its automation.  Very important going forwards.
The todo's, etc are in the Projects (1) tab visible as a tree.
